language: python
python:
- 3.6
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,cython numpy scipy cython
  - pip install pyxb
  - pip install --no-use-pep517 -e .
  - pip install pytest-cov
  - pip install coveralls
  - pip install PyGithub==1.39
  - pip install flake8==3.4.1

before_script:
  - flake8 --count --ignore W503,F401 --exclude teaser/data/bindings,doc,tests --max-line-length=120
master:
  script:
  - py.test --cov=teaser
  after_success:
  - coveralls

script:
- py.test --cov=teaser --ignore=tests/test_modelicaversion.py
after_success:
- coveralls

deploy:
  provider: pypi
  user: teaser_github
  password:
    secure: UQ/Iuz6Fyb+6gw64MQ8ES8cBGhI+lXTNc+CK8/7XmYYP5/xsVGntAQTYTSCBuuDnjsErPpgU11cY5ZV4hHFRzuYTcPgIByLcTBtfJ/eKCztDw+b4FKK67jBmdJtbXNSVQ4oDIRLH/NS9MJAHBB9+CFR0wpDxgvQ7tuthAKsBr+7ELv68KAy6K6pCjjAEcTJa8dT/l6bioDjVXu1bnhgbbfHANhZRO6LSMdyYzFBKc/LDZnZD/LjBth3pGxx16Tq1Fk/3mRX3pW/FbdWqhYIqm/ty4l35j+UA46sQql1V9RRwuWVSoxE1fRxWywlXpMf/37zMaIwwIxQqvC78E1jNU3GFrsCxm++dhqTnponiGwzNG3pjOTDZmXpmWeJeFMfEPHfOGQqVz4V5HJiTqBmU8elw/+Fq9nGkQZRCElRaPnpf5Z8PcED1cB13cHtzjKW7yKSm5F5TTS8vBUQ0apa5R5XyC5lxvNlBUibppBz5r9I5SxaCPu36IY6Mga1g5ooCHeV06rE/Uzjczyf6otXSILH0ZUq5bC82nN5TzJZEzy0RcIyQqHNPOdDjcdJYOKnb7qyS1nlb8wzNbP5rWOSD5P2RjcYGcWH1I1Dw0Bs7GiwtiNv8Uk48AkxBFrRyhLptT2Yjja4YJZDJuF82CmY1MB1FJOuNS0VIKfmsWzOhlOw=
  on:
    tags: true
    all_branches: true
