[[ExampleFile]]
filename = "teaser/examples/e1_generate_archetype.py"
func_name = "example_generate_archetype"
md_path = "docs/examples"
ipynb_path = "docs/jupyter_notebooks"

[[ExampleFile]]
filename = "teaser/examples/e2_export_aixlib_models.py"
func_name = "example_export_aixlib"
md_path = "docs/examples"
ipynb_path = "docs/jupyter_notebooks"

[[ExampleFile]]
filename = "teaser/examples/e3_export_ibpsa_models.py"
func_name = "example_export_ibpsa"
md_path = "docs/examples"
ipynb_path = "docs/jupyter_notebooks"

[[ExampleFile]]
filename = "teaser/examples/e4_save.py"
func_name = "example_save"
md_path = "docs/examples"
ipynb_path = "docs/jupyter_notebooks"

[[ExampleFile]]
filename = "teaser/examples/e5_load.py"
func_name = "example_load"
md_path = "docs/examples"
ipynb_path = "docs/jupyter_notebooks"

[[ExampleFile]]
filename = "teaser/examples/e6_generate_buildings.py"
func_name = "example_create_building"
md_path = "docs/examples"
ipynb_path = "docs/jupyter_notebooks"

[[ExampleFile]]
filename = "teaser/examples/e7_retrofit.py"
func_name = "example_retrofit_building"
md_path = "docs/examples"
ipynb_path = "docs/jupyter_notebooks"
